apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PyPDF2
  description: A utility to read and write PDFs with Python
  annotations:
    business-unit: EverHealth
    github.com/project-slug: drchrono/PyPDF2
    product: DRC
spec:
  type: service
  lifecycle: production
  owner: EverHealth
  implementation:
    languages:
    - Python
    - Shell
